repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
    - id: ruff # Run the linter
      args: [--fix] # enable automatic fixes
    - id: ruff-format # Run the formatter
