[project]
name = "data-science-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "ruff>=0.9.2",
]

[tool.ruff]
exclude = [
    ".git",
    ".ipynb",
    ".ipynb_checkpoints",
    ".ruff_cache",
    ".venv",
    ".vscode",
]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C", "B", "RUF"]
ignore = ["E501"] # line too long
fixable = ["ALL"] # Allow fix for all enabled rules
unfixable = []

[tool.ruff.format]
indent-style = "space"
