name: Terraform Dry Run 

on:
  push:
    paths:
      - "jobs/**"
      - "terraform/**"
jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v4

      #1) Zip any job/* folder
      - name: Find jobs
        id: jobs
        run: |
          if [-d jobs]; then
            ls -1 jobs > jobs.list || true
          fi
          echo "jobs=$(cat jobs.list 2>/dev/null | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Zip changed or existing jobs
        if: steps.jobs.outputs.jobs != ''
        run: |
         for j in ${{ steps.jobs.outputs.jobs }}; do
           (cd jobs/$j && zip -r ../../${j}.zip . -x "__pycache__/*" "*.pyc") || true
         done
      - name: Upload demo zips as workflow artifacts
        uses: actions/upload-artifacts@v4
        with: 
         name: job-zips
         path: "*.zip"
         if-no-files-found: ignore

      #2) Terraform sanity: init/validate/plan
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init 
        run: terraform -chdir=terraform/envs/dev init -backend=false

      - name: Terraform validate
        run: terraform -chdir=terraform/envs/dev init validate

      - name: Terraform plan
        run: terraform -chdir=terraform/envs/dev init plan -var-file=dev.tfvars -input=false
